/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { ReentrantAttacker, ReentrantAttackerInterface } from "../../test/ReentrantAttacker.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_escrow",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "attackCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "escrow",
    "outputs": [
      {
        "internalType": "contract OptimisticEscrow",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "onTokenReceived",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_jobId",
        "type": "uint256"
      }
    ],
    "name": "setTarget",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "targetJobId",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060405161028538038061028583398101604081905261002e91610052565b5f80546001600160a01b0319166001600160a01b039290921691909117905561007f565b5f60208284031215610062575f80fd5b81516001600160a01b0381168114610078575f80fd5b9392505050565b6101f98061008c5f395ff3fe608060405234801561000f575f80fd5b5060043610610055575f3560e01c80631035fb5c14610059578063407c28211461006e578063491531731461008a578063b480eac014610093578063e2fdcc17146100a6575b5f80fd5b61006c610067366004610153565b6100d0565b005b61007760025481565b6040519081526020015b60405180910390f35b61007760015481565b61006c6100a1366004610188565b600155565b5f546100b8906001600160a01b031681565b6040516001600160a01b039091168152602001610081565b6002545f0361014f5760028054905f6100e88361019f565b90915550505f546001546040516309cc1d1d60e11b81526001600160a01b03909216916313983a3a916101219160040190815260200190565b5f604051808303815f87803b158015610138575f80fd5b505af115801561014a573d5f803e3d5ffd5b505050505b5050565b5f8060408385031215610164575f80fd5b82356001600160a01b038116811461017a575f80fd5b946020939093013593505050565b5f60208284031215610198575f80fd5b5035919050565b5f600182016101bc57634e487b7160e01b5f52601160045260245ffd5b506001019056fea2646970667358221220fe6cbddc4fb20d9e4b9727767e82d50a31741840e5d56fe29dbc0e4d760b8b1c64736f6c63430008180033";

  
      type ReentrantAttackerConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ReentrantAttackerConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ReentrantAttacker__factory extends ContractFactory {
    
      constructor(...args: ReentrantAttackerConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_escrow: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_escrow, overrides || {});
    };
    override deploy(_escrow: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_escrow, overrides || {}) as Promise<ReentrantAttacker & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ReentrantAttacker__factory {
      return super.connect(runner) as ReentrantAttacker__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ReentrantAttackerInterface {
      return new Interface(_abi) as ReentrantAttackerInterface;
    }
    
    override attach(address: string | Addressable): ReentrantAttacker {
      return super.attach(address) as ReentrantAttacker;
    }
  static connect(address: string, runner?: ContractRunner | null): ReentrantAttacker {
      return new Contract(address, _abi, runner) as unknown as ReentrantAttacker;
    }
  }

  
  