/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface OptimisticEscrowInterface extends Interface {
    getFunction(nameOrSignature: "MAX_FEE_BPS" | "REVIEW_WINDOW" | "acceptJob" | "accumulatedFees" | "approveAndRelease" | "arbiter" | "claimAfterWindow" | "createJob" | "feeBps" | "jobCount" | "jobs" | "logProgress" | "owner" | "paymentToken" | "raiseDispute" | "renounceOwnership" | "resolveDispute" | "setArbiter" | "setFeeBps" | "submitWork" | "transferOwnership" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeRaised" | "DisputeResolved" | "FeesWithdrawn" | "FundsReleased" | "JobAccepted" | "JobCreated" | "OwnershipTransferred" | "ProgressLogged" | "WorkSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'REVIEW_WINDOW', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptJob', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'approveAndRelease', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'arbiter', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimAfterWindow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createJob', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'feeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'jobCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'jobs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'logProgress', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setArbiter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setFeeBps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitWork', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawFees', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'REVIEW_WINDOW', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveAndRelease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'arbiter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimAfterWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jobCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jobs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logProgress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setArbiter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitWork', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace DisputeRaisedEvent {
      export type InputTuple = [jobId: BigNumberish, raisedBy: AddressLike, reason: string];
      export type OutputTuple = [jobId: bigint, raisedBy: string, reason: string];
      export interface OutputObject {jobId: bigint, raisedBy: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [jobId: BigNumberish, amountToFreelancer: BigNumberish, amountToClient: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [jobId: bigint, amountToFreelancer: bigint, amountToClient: bigint, fee: bigint];
      export interface OutputObject {jobId: bigint, amountToFreelancer: bigint, amountToClient: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsReleasedEvent {
      export type InputTuple = [jobId: BigNumberish, netAmount: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [jobId: bigint, netAmount: bigint, fee: bigint];
      export interface OutputObject {jobId: bigint, netAmount: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobAcceptedEvent {
      export type InputTuple = [jobId: BigNumberish, freelancer: AddressLike];
      export type OutputTuple = [jobId: bigint, freelancer: string];
      export interface OutputObject {jobId: bigint, freelancer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobCreatedEvent {
      export type InputTuple = [jobId: BigNumberish, client: AddressLike, freelancer: AddressLike, amount: BigNumberish, taskTitle: string];
      export type OutputTuple = [jobId: bigint, client: string, freelancer: string, amount: bigint, taskTitle: string];
      export interface OutputObject {jobId: bigint, client: string, freelancer: string, amount: bigint, taskTitle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProgressLoggedEvent {
      export type InputTuple = [jobId: BigNumberish, percent: BigNumberish, note: string];
      export type OutputTuple = [jobId: bigint, percent: bigint, note: string];
      export interface OutputObject {jobId: bigint, percent: bigint, note: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkSubmittedEvent {
      export type InputTuple = [jobId: BigNumberish, submittedAt: BigNumberish, submissionLink: string];
      export type OutputTuple = [jobId: bigint, submittedAt: bigint, submissionLink: string];
      export interface OutputObject {jobId: bigint, submittedAt: bigint, submissionLink: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface OptimisticEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): OptimisticEscrow;
    waitForDeployment(): Promise<this>;

    interface: OptimisticEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    REVIEW_WINDOW: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptJob: TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    approveAndRelease: TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    arbiter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    claimAfterWindow: TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createJob: TypedContractMethod<
      [freelancer: AddressLike, amount: BigNumberish, taskTitle: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    feeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    jobCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    jobs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, string, string] & {client: string, freelancer: string, amount: bigint, releasedAmount: bigint, submittedAt: bigint, status: bigint, taskTitle: string, submissionLink: string }],
      'view'
    >
    

    
    logProgress: TypedContractMethod<
      [jobId: BigNumberish, percent: BigNumberish, note: string, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    raiseDispute: TypedContractMethod<
      [jobId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [jobId: BigNumberish, amountToFreelancer: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setArbiter: TypedContractMethod<
      [newArbiter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeBps: TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitWork: TypedContractMethod<
      [jobId: BigNumberish, submissionLink: string, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawFees: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'REVIEW_WINDOW'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptJob'): TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approveAndRelease'): TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'arbiter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'claimAfterWindow'): TypedContractMethod<
      [jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createJob'): TypedContractMethod<
      [freelancer: AddressLike, amount: BigNumberish, taskTitle: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'jobCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'jobs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, string, string] & {client: string, freelancer: string, amount: bigint, releasedAmount: bigint, submittedAt: bigint, status: bigint, taskTitle: string, submissionLink: string }],
      'view'
    >;
getFunction(nameOrSignature: 'logProgress'): TypedContractMethod<
      [jobId: BigNumberish, percent: BigNumberish, note: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [jobId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [jobId: BigNumberish, amountToFreelancer: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setArbiter'): TypedContractMethod<
      [newArbiter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeBps'): TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitWork'): TypedContractMethod<
      [jobId: BigNumberish, submissionLink: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'FundsReleased'): TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
getEvent(key: 'JobAccepted'): TypedContractEvent<JobAcceptedEvent.InputTuple, JobAcceptedEvent.OutputTuple, JobAcceptedEvent.OutputObject>;
getEvent(key: 'JobCreated'): TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProgressLogged'): TypedContractEvent<ProgressLoggedEvent.InputTuple, ProgressLoggedEvent.OutputTuple, ProgressLoggedEvent.OutputObject>;
getEvent(key: 'WorkSubmitted'): TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;

    filters: {
      
      'DisputeRaised(uint256,address,string)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(uint256,uint256,uint256,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'FundsReleased(uint256,uint256,uint256)': TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
      FundsReleased: TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
    

      'JobAccepted(uint256,address)': TypedContractEvent<JobAcceptedEvent.InputTuple, JobAcceptedEvent.OutputTuple, JobAcceptedEvent.OutputObject>;
      JobAccepted: TypedContractEvent<JobAcceptedEvent.InputTuple, JobAcceptedEvent.OutputTuple, JobAcceptedEvent.OutputObject>;
    

      'JobCreated(uint256,address,address,uint256,string)': TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
      JobCreated: TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProgressLogged(uint256,uint8,string)': TypedContractEvent<ProgressLoggedEvent.InputTuple, ProgressLoggedEvent.OutputTuple, ProgressLoggedEvent.OutputObject>;
      ProgressLogged: TypedContractEvent<ProgressLoggedEvent.InputTuple, ProgressLoggedEvent.OutputTuple, ProgressLoggedEvent.OutputObject>;
    

      'WorkSubmitted(uint256,uint256,string)': TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
      WorkSubmitted: TypedContractEvent<WorkSubmittedEvent.InputTuple, WorkSubmittedEvent.OutputTuple, WorkSubmittedEvent.OutputObject>;
    
    };
  }