/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MockINRFeed, MockINRFeedInterface } from "../MockINRFeed.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "_initialAnswer",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "answer",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "decimals",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "description",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "roundId",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "answer_",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "startedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "updatedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "answeredInRound",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "_newAnswer",
        "type": "int256"
      }
    ],
    "name": "updateAnswer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060405161032f38038061032f83398101604081905261002e91610061565b5f80546001600160a01b03191633179055600155600280546101086001600160581b031990911617905542600355610078565b5f60208284031215610071575f80fd5b5051919050565b6102aa806100855f395ff3fe608060405234801561000f575f80fd5b5060043610610060575f3560e01c8063313ce567146100645780637284e4161461008857806385bb7d69146100b35780638da5cb5b146100ca578063a87a20ce146100f4578063feaf968c14610109575b5f80fd5b6002546100719060ff1681565b60405160ff90911681526020015b60405180910390f35b6040805180820182526009815268125394880bc81554d160ba1b6020820152905161007f91906101e0565b6100bc60015481565b60405190815260200161007f565b5f546100dc906001600160a01b031681565b6040516001600160a01b03909116815260200161007f565b61010761010236600461022c565b610147565b005b600254600154600354604080516101009094046001600160501b0316808552602085019390935283018190526060830152608082015260a00161007f565b5f546001600160a01b031633146101905760405162461bcd60e51b81526020600482015260096024820152682737ba1037bbb732b960b91b604482015260640160405180910390fd5b60018181556002805461010090046001600160501b0316916101b183610243565b91906101000a8154816001600160501b0302191690836001600160501b03160217905550504260038190555050565b5f602080835283518060208501525f5b8181101561020c578581018301518582016040015282016101f0565b505f604082860101526040601f19601f8301168501019250505092915050565b5f6020828403121561023c575f80fd5b5035919050565b5f6001600160501b0380831681810361026a57634e487b7160e01b5f52601160045260245ffd5b600101939250505056fea26469706673582212205b5edf10ee9a7718d3af425899c06e2aaeb535ed08ef24f4e1fa71452c1589b264736f6c63430008180033";

  
      type MockINRFeedConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockINRFeedConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockINRFeed__factory extends ContractFactory {
    
      constructor(...args: MockINRFeedConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_initialAnswer: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_initialAnswer, overrides || {});
    };
    override deploy(_initialAnswer: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_initialAnswer, overrides || {}) as Promise<MockINRFeed & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockINRFeed__factory {
      return super.connect(runner) as MockINRFeed__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockINRFeedInterface {
      return new Interface(_abi) as MockINRFeedInterface;
    }
    
    override attach(address: string | Addressable): MockINRFeed {
      return super.attach(address) as MockINRFeed;
    }
  static connect(address: string, runner?: ContractRunner | null): MockINRFeed {
      return new Contract(address, _abi, runner) as unknown as MockINRFeed;
    }
  }

  
  