/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ReentrantAttackerInterface extends Interface {
    getFunction(nameOrSignature: "attackCount" | "escrow" | "onTokenReceived" | "setTarget" | "targetJobId"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'attackCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrow', values?: undefined): string;
encodeFunctionData(functionFragment: 'onTokenReceived', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTarget', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'targetJobId', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'attackCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onTokenReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'targetJobId', data: BytesLike): Result;
  }

  

  export interface ReentrantAttacker extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReentrantAttacker;
    waitForDeployment(): Promise<this>;

    interface: ReentrantAttackerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attackCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    escrow: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    onTokenReceived: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTarget: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    targetJobId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attackCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'escrow'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'onTokenReceived'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTarget'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'targetJobId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }